import Nav from '@/components/layout/nav'
import './globals.css'
import {Inter} from 'next/font/google'
import {Suspense} from 'react'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Suspense fallback="...">
                    {/* @ts-expect-error Async Server Component */}
                    <Nav />
                </Suspense>
                <main>{children}</main>
            </body>
        </html>
    )
}
